# Generated by Django 6.0.6 on 2026-06-09 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentoratPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('offre', 'Offre de mentorat'), ('demande', 'Demande de mentorat')], default='offre', max_length=10)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('filiere', models.CharField(choices=[('Informatique', 'Informatique'), ('Data Science', 'Data Science'), ('Finance', 'Finance'), ('Management', 'Management'), ('Marketing', 'Marketing'), ('Design', 'Design'), ('Cybersécurité', 'Cybersécurité')], default='Informatique', max_length=120)),
                ('competences', models.CharField(help_text='Sépare les compétences par des virgules', max_length=250)),
                ('disponibilites', models.CharField(blank=True, default='Lundi-Vendredi', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('mentor', 'Mentor'), ('mentee', 'Mentoré'), ('both', 'Mentor/Bénéficiaire')], default='both', max_length=10)),
                ('filiere', models.CharField(choices=[('Informatique', 'Informatique'), ('Data Science', 'Data Science'), ('Finance', 'Finance'), ('Management', 'Management'), ('Marketing', 'Marketing'), ('Design', 'Design'), ('Cybersécurité', 'Cybersécurité')], default='Informatique', max_length=120)),
                ('competences', models.CharField(blank=True, help_text='Sépare les compétences par des virgules', max_length=300)),
                ('disponibilites', models.CharField(blank=True, default='Lundi-Vendredi', max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
