# Generated by Django 6.0.6 on 2026-06-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_add_intelligent_matching'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='identite_professionnelle',
            field=models.TextField(blank=True, help_text='Raconte ton identite professionnelle ou tes objectifs de carriere'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interets_academiques',
            field=models.CharField(blank=True, help_text='Ex: developpement web, UI/UX, data science, algorithmique', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='motivation',
            field=models.TextField(blank=True, help_text='Pourquoi tu veux participer au mentorat et quels objectifs tu vises'),
        ),
        migrations.AddField(
            model_name='profile',
            name='niveau_etude',
            field=models.CharField(blank=True, help_text='Ex: Bac+3, Master 1, annee 2', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='promotion',
            field=models.CharField(blank=True, help_text='Ex: Promo 2026, Promo 2027', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='style_mentorat',
            field=models.CharField(blank=True, help_text='Decris ton style de mentorat ou d\'accompagnement', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='ue_faibles',
            field=models.CharField(blank=True, help_text='Unites d\'enseignement a renforcer, separees par des virgules', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='ue_fortes',
            field=models.CharField(blank=True, help_text='Unites d\'enseignement fortes, separees par des virgules', max_length=300),
        ),
    ]
